name: SavageGames
description: SavageGames plugin.
author: AlbireoX
website: http://savagegames.net/
version: 0.1

main: net.savagegames.savagegames.SavageGames

commands:
  savagegames:
    description: SavageGames main command.
    usage: /savagegames [args]
  class:
    description: Selects a class.
    usage: /class <class name>
